
-- C:\h2-2022-06-13\h2>cd bin

-- C:\h2-2022-06-13\h2\bin>h2.bat

drop table if exists member CASCADE;
create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);